- name: Remove pgAdmin deployment
  command: kubectl delete deployment pgadmin4 -n postgres
  register: pgadmin_cleanup
  changed_when: pgadmin_cleanup.rc == 0
  ignore_errors: true

- name: Remove pgAdmin service
  command: kubectl delete service pgadmin4 -n postgres
  register: pgadmin_service_cleanup
  changed_when: pgadmin_service_cleanup.rc == 0
  ignore_errors: true

- name: Remove pgAdmin PVC
  command: kubectl delete pvc pgadmin-pvc -n postgres
  register: pgadmin_pvc_cleanup
  changed_when: pgadmin_pvc_cleanup.rc == 0
  ignore_errors: true

- name: Remove pgAdmin servers ConfigMap
  command: kubectl delete configmap pgadmin-servers -n postgres
  register: pgadmin_configmap_cleanup
  changed_when: pgadmin_configmap_cleanup.rc == 0
  ignore_errors: true

- name: Remove PostgreSQL Helm release
  command: helm uninstall postgresql -n postgres
  register: postgresql_cleanup
  changed_when: postgresql_cleanup.rc == 0
  ignore_errors: true

- name: Wait for pods to terminate
  command: kubectl wait --for=delete pod --all -n postgres --timeout=120s
  register: pods_cleanup
  changed_when: pods_cleanup.rc == 0
  ignore_errors: true

- name: Remove PostgreSQL namespace
  command: kubectl delete namespace postgres
  register: namespace_cleanup
  changed_when: namespace_cleanup.rc == 0
  ignore_errors: true

- name: Remove temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/pgadmin-deployment.yaml
  ignore_errors: true 