apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-test
  namespace: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres-restore-test
        image: postgres:17
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
        - name: POSTGRES_DB
          value: "myapp"
        - name: SCHEMA_TARGET
          value: "test"
        command:
        - /bin/bash
        - /scripts/restore.sh
        volumeMounts:
        - name: backup-scripts
          mountPath: /scripts
        - name: backup-storage
          mountPath: /backup
      volumes:
      - name: backup-scripts
        configMap:
          name: postgres-backup-scripts
          defaultMode: 0755
      - name: backup-storage
        persistentVolumeClaim:
          claimName: postgres-backup-pvc
      restartPolicy: Never 