---
- name: Clean up Jenkins completely
  hosts: servers
  become: yes
  tasks:
    - name: Uninstall Jenkins Helm release
      shell: |
        helm uninstall jenkins -n jenkins
      environment:
        KUBECONFIG: /home/{{ ansible_user }}/k3s.yaml
      ignore_errors: yes

    - name: Delete Jenkins PVCs
      shell: |
        kubectl delete pvc --all -n jenkins
      environment:
        KUBECONFIG: /home/{{ ansible_user }}/k3s.yaml
      ignore_errors: yes

    - name: Delete Jenkins namespace
      shell: |
        kubectl delete namespace jenkins --force --grace-period=0
      environment:
        KUBECONFIG: /home/{{ ansible_user }}/k3s.yaml
      ignore_errors: yes

    - name: Remove Jenkins values file
      file:
        path: /home/{{ ansible_user }}/jenkins-values.yaml
        state: absent
      ignore_errors: yes 