controller:
  jcasc:
    enabled: false
    configScripts: {}
  serviceType: NodePort
  installPlugins:
    - kubernetes:1.30.1
    - workflow-aggregator:2.6
    - git:4.14.3
    - credentials:1415.v831096eb_5534
    - credentials-binding:687.v619cb_15e923f
    - plain-credentials:195.vb_906e9073dee
    - ssh-credentials:355.v9b_e5b_cde5003
    - git-client:6.1.3
    - scm-api:704.v3ce5c542825a_
    - cloudbees-folder:6.1012.v79a_86a_1ea_c1f
    - structs:343.vdcf37b_a_c81d5
    - script-security:1373.vb_b_4a_a_c26fa_00
    - display-url-api:2.209.v582ed814ff2f
    - matrix-project:849.v0cd64ed7e531
    - docker-commons:451.vd12c371eeeb_3
    - workflow-job:1520.v56d65e3b_4566
    - workflow-support:968.v8f17397e87b_8
    - workflow-step-api:700.v6e45cb_a_5a_a_21
    - workflow-basic-steps:1079.vce64b_a_929c5a_
    - workflow-cps:4106.v7a_8a_8176d450
    - workflow-scm-step:437.v05a_f66b_e5ef8
    - workflow-durable-task-step:1405.v1fcd4a_d00096
    - workflow-multibranch:806.vb_b_688f609ee9
    - pipeline-stage-view:2.38
    - pipeline-input-step:517.vf8e782ee645c
    - pipeline-stage-step:322.vecffa_99f371c
    - pipeline-model-definition:2.2255.v56a_15e805f12
    - pipeline-model-api:2.2255.v56a_15e805f12
    - pipeline-model-extensions:2.2255.v56a_15e805f12
    - pipeline-stage-tags-metadata:2.2255.v56a_15e805f12
    - pipeline-rest-api:2.38
    - pipeline-build-step:567.vea_ce550ece97
    - checks-api:370.vb_61a_c57328f3
    - echarts-api:5.6.0-4
    - bootstrap5-api:5.3.5-1
    - data-tables-api:2.2.2-1
    - font-awesome-api:6.7.2-1
    - ionicons-api:88.va_4187cb_eddf1
    - jquery3-api:3.7.1-3
    - plugin-util-api:6.1.0
    - prism-api:1.30.0-1
    - commons-lang3-api:3.17.0-87.v5cf526e63b_8b_
    - commons-text-api:1.13.0-153.v91dcd89e2a_22
    - jackson2-api:2.18.3-402.v74c4eb_f122b_2
    - json-api:20250107-125.v28b_a_ffa_eb_f01
    - snakeyaml-api:2.3-125.v4d77857a_b_402
    - joda-time-api:2.14.0-127.v7d9da_295a_d51
    - jakarta-activation-api:2.1.3-2
    - jakarta-mail-api:2.1.3-2
    - javax-activation-api:1.2.0-8
    - jaxb:2.3.9-133.vb_ec76a_73f706
    - bouncycastle-api:2.30.1.80-256.vf98926042a_9b_
    - caffeine-api:3.2.0-166.v72a_6d74b_870f
    - asm-api:9.8-135.vb_2239d08ee90
    - instance-identity:203.v15e81a_1b_7a_38
    - mina-sshd-api-common:2.15.0-161.vb_200831a_c15b_
    - mina-sshd-api-core:2.15.0-161.vb_200831a_c15b_
    - sshd:3.353.v2b_d33c46e970
    - eddsa-api:0.3.0.1-19.vc432d923e5ee
    - gson-api:2.13.1-139.v4569c2ef303f
    - okhttp-api:4.11.0-189.v976fa_d3379d6
    - variant:70.va_d9f17f859e0
    - kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
    - kubernetes-credentials:192.v4d5b_1c429d17
    - authentication-tokens:1.131.v7199556c3004
    - antisamy-markup-formatter:173.v680e3a_b_69ff3
    - apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  javaOpts: >-
    -Xms512m
    -Xmx1024m
    -XX:MaxRAM=2g
    -Dhudson.model.DirectoryBrowserSupport.CSP=""
  jenkinsOpts: "--prefix=/jenkins"
  admin:
    username: admin
    password: admin123
  serviceType: NodePort
  nodePort: 30000
  servicePort: 8080
  targetPort: 8080
  installLatestSpecifiedPlugins: true
  installLatestPlugins: false
  enableRawHtmlMarkupFormatter: true
  serviceAccount:
    create: true
    annotations: {}
    name: jenkins
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "local-path"
    accessMode: ReadWriteOnce
  livenessProbe:
    httpGet:
      path: /jenkins/login
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /jenkins/login
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10
  startupProbe:
    httpGet:
      path: /jenkins/login
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 30

rbac:
  create: true
  readSecrets: true

serviceAccount:
  create: true
  annotations: {}
  name: jenkins

serviceType: NodePort
servicePort: 8080
targetPort: 8080 