---
- name: Basic Server Setup
  hosts: servers
  become: yes
  tasks:
    - include_tasks: setup-tasks.yml

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install common packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - htop
          - curl
          - wget
          - git
          - ufw
          - fail2ban

    - name: Configure timezone
      timezone:
        name: UTC

    - name: Set up basic firewall
      ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Enable and start fail2ban
      service:
        name: fail2ban
        state: started
        enabled: yes

    # --- K3s Install ---
    - name: Install k3s (Kubernetes)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      shell: |
        k3s kubectl get node
      register: k3s_ready
      retries: 10
      delay: 10
      until: k3s_ready.rc == 0

    - name: Fix k3s config permissions for kubectl access
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'
        owner: root
        group: root

    # --- Helm Install ---
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3.sh
        mode: '0755'

    - name: Install Helm
      shell: bash /tmp/get-helm-3.sh
      args:
        creates: /usr/local/bin/helm

- import_playbook: ingress/setup.yml 